import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Redux Tooolkit",
  description: "Generated by Faizan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-sans bg-gray-950"
      >
        {children}
      </body>
    </html>
  );
}
